library(data.table)
allData <- read.table("household_power_consumption.txt",header=TRUE,sep=";",na.strings="?")
twoDayData <- as.data.table(allData[allData$Date=="1/2/2007"|allData$Date=="2/2/2007",])
twoDayData[,datetime:= as.POSIXct(strptime(paste(Date,Time),"%d/%m/%Y %H:%M:%S"),tz="UTC")]  # must use tz and specify valid time zone to make it work
png("plot4.png",width=480,height=480)
par(mfrow=c(2,2))
with(twoDayData, {
   plot(datetime,Global_active_power,type="l",xlab="",ylab="Global Active Power (kilowatts)")
   plot(datetime,Voltage,type="l")
   plot(datetime,Sub_metering_1,type="l",xlab="",ylab="Energy sub metering")
      lines(datetime,Sub_metering_2,col="red")
      lines(datetime,Sub_metering_3,col="blue")
      legend("topright",bty="n",lty,lwd=1,col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
   plot(datetime,Global_reactive_power,type="l")
})
dev.off()
